### ISSUE TITLE
axis conventions?

### ISSUE THREAD

**Issue by seanny1986** [ratcave/ratcave#68]
I'm trying to use ratcave to visualize an aircraft simulation, but I can't seem to find any good information on the axes conventions in the documentation.

I've figured out:
RC is using a right-handed axis system where the z-axis is coming out of the page, x is positive to the right, and y is positive in the upwards direction.

However:
I don't know if this is for the global coordinate system, the mesh coordinate system, or both. 
Also, when I take the example to rotate the torus about one axis, it works for two of the axes, but not the third. This makes sense if it's trying to rotate about the z-axis, and the object is symmetrical about that axis. However, when I try to set the orientation of the torus (I've tried using position_global and orientation) so that it's not symmetrical face-on, it still doesn't rotate. I'm guessing this is because it's rotating about the body axis system, and when I change the orientation, so too does the direction of the axis of rotation. I.e. it's still rotating about its axis of symmetry, so I can't see it.

My questions are:
What functions set rotations in the global frame versus the global frame? I'd like to be able to set the attitude of the aircraft using Euler angles or quaternions, but I'm operating in an NED coordinate system as is conventional for aircraft simulation. I can convert this to ENU pretty easily, and then rotate it into the coordinate system used by ratcave, but whenever I try this it doesn't come out correctly. Finally, what's going on when I try to change the orientation of the object so that it's no longer symmetrical about the axis of rotation, and it still doesn't rotate?

Any help on this would be greatly appreciated.

Cheers!

**Comment by DavidLanders95** [comment]
Hey Seanny, did you ever find an answer to this? I'm come accross the same issue and can't find any other info on it.

**Comment by gadese** [comment]
@seanny1986 @DavidLanders95 

Did any of you ever figure it out? I have the exact same issue and I've been pulling my hair for the past 2 weeks trying to set my orientation using Euler angles/quaternions.

The Ratcave source code mentions XYZ Euler, but in practice it doesn't seem to be what I observe.

**Comment by nickdelgrosso** [comment]
Hi @gadese, did you work this out?  As mentioned in the readme, I abandoned this project years ago, but would be happy to pair program with you to fix the project.  As I recall, orientations were what I struggled with the most, so it's entirely possible that there is a mistake somewhere in there.

**Comment by DavidLanders95** [comment]
> @seanny1986 @DavidLanders95
> 
> Did any of you ever figure it out? I have the exact same issue and I've been pulling my hair for the past 2 weeks trying to set my orientation using Euler angles/quaternions.
> 
> The Ratcave source code mentions XYZ Euler, but in practice it doesn't seem to be what I observe.

I gave up on this programme and switched to pyqtgraph for my 3D visualisation needs. It works for me but it might not be for everyone. It at least has lots of very nice examples which make it easy to use.
