### ISSUE TITLE
Rendering two camera viewpoints in the one scene? 

### ISSUE THREAD

**Issue by DavidLanders95** [ratcave/ratcave#83]
Is it possible to render a picture in picture view with Ratcave using two camera objects? I see that tutorial 4 appears to use two camera viewpoints, but I cannot get that tutorial to run. 

Does a dev have any suggestion on how to render such a view point?

**Comment by nickdelgrosso** [comment]
Hi @DavidLanders95 ,

Yes, it's possible.  The approach would be to use an FBO to render onto a quad's texture from one camera angle, and position the quad (a rectangular plane) in the corner of the screen.  The main camera view could also be done this way (with a fullscreen-quad), or could just be rendered directly to screen.
